# Generated by Django 3.2.4 on 2021-12-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20211214_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='breed',
            field=models.CharField(default='unknown', max_length=2000),
        ),
    ]
