# Generated by Django 3.2.4 on 2021-12-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='breed',
        ),
    ]
